strategy:
  matrix:
    linux-stable:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: stable
    linux-beta:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: beta

pool:
  vmImage: $(imageName)

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Windows install rust
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: rustup component add clippy rustfmt
    displayName: install clipppy and rustfmt

  - script: cargo fmt --all -- --check
    displayName: rustfmt
  - script: cargo build --all
    displayName: Cargo build
  - script: cargo clippy --all-targets -- -D warnings
    displayName: clippy
  - script: cargo test --all
    displayName: Cargo test


  - script: cargo fmt --all -- --check
    displayName: rustfmt (ioym)
    workingDirectory: ioym
  - script: cargo build --all
    displayName: Cargo build (ioym)
    workingDirectory: ioym
  - script: cargo clippy --all-targets -- -D warnings
    displayName: clippy (ioym)
    workingDirectory: ioym
  - script: cargo test --all
    displayName: Cargo test (ioym)
    workingDirectory: ioym

  - script: cargo fmt --all -- --check
    displayName: rustfmt (loggestd)
    workingDirectory: loggestd
  - script: cargo build --all
    displayName: Cargo build (loggestd)
    workingDirectory: loggestd
  - script: cargo clippy --all-targets -- -D warnings
    displayName: clippy (loggestd)
    workingDirectory: loggestd
  - script: cargo test --all
    displayName: Cargo test (loggestd)
    workingDirectory: loggestd
