[package]
name = "loggestd"
version = "0.1.0"
authors = ["Roey Darwish Dror"]
edition = "2018"

[dependencies]
tokio = "0.1.21"
bytes = "0.4.12"
byteorder = "1.3.2"
futures = "0.1"
log = "0.4.6"
env_logger = "0.6.1"
